fixed `yarn dev` not being cross platform
SuperteamDAO/earn pull request #319
Opened 2023-12-19 09:18 UTC by Shiva953

## What does this PR do?
This PR makes the `yarn dev` command cross platform by tweaking the `dev` and `start` scripts in the package.json, by using `set NODE_ENV=development && next dev` instead of `NODE_ENV=development next dev`, so that it can be compatible on windows as well other than linux and macOS.

## How should this be manually tested?
Run the `yarn dev` command on windows

## What are the relevant issues?
Fixes #309

2023-12-19 09:19 UTC, Shiva953 commented
@a20hek

2023-12-23 14:22 UTC, Shiva953 commented
any updates on this?

2023-12-24 19:09 UTC, a20hek commented
> any updates on this?

have you confirmed this fix on a laptop with windows?

2023-12-28 23:22 UTC, a20hek requested changes
does not work on macOS

2023-12-30 08:52 UTC, a20hek commented
hey @Shiva953 i am gonna close this PR as we have to implement this urgently; so i am gonna be moving forward with this. thank you for raising this PR!

2023-12-30 08:52 UTC, closed without merging