implemented auto-generating and editable slugs
SuperteamDAO/earn pull request #492
Opened 2024-03-21 18:18 UTC by Sajal0208

## What does this PR do?

This PR resolves the issue mentioned in https://github.com/SuperteamDAO/earn/issues/479

Open to any suggestions which might improve the UI or the UX of the Form.

2024-03-28 08:45 UTC, a20hek requested changes
would like the implementation to have 
1. the initial slug should not be a random slug, but a slug code similar to https://github.com/SuperteamDAO/earn/blob/main/src/pages/api/bounties/create.ts#L9-L44
2. slug should change on title input change, but again – not a random change, it should fetch and check what the appropriate slug should be for that particular title, and then load that particular slug

2024-03-29 09:58 UTC, a20hek requested changes
please perform the requested changes, and also fix naming of functions 
rest looks good to me

2024-03-29 09:58 UTC, a20hek commented on src/features/sponsor-dashboard/components/Submissions/SubmissionDetails.tsx
> +      const transaction = new Transaction();
my changes from a different PR are showing up in this PR's diff
so i would suggest you to open a separate PR by checking out from the latest staging branch

2024-03-29 09:58 UTC, a20hek commented on src/pages/api/listings/slug.ts
> +        isActive: true,
remove `isActive: true`

2024-03-29 10:32 UTC, Sajal0208 commented
@a20hek done with all the changes. 
opened a new PR: #516 
thankyou :)

2024-03-29 10:40 UTC, a20hek commented
> @a20hek done with all the changes. opened a new PR: #516 thankyou :)

cool, thanks
hence closing this PR

2024-03-29 10:40 UTC, closed without merging