implemented auto-generating unique slugs
SuperteamDAO/earn pull request #516
Opened 2024-03-29 10:27 UTC by Sajal0208

## What does this PR do?

This PR resolves the issue mentioned in #479

2024-03-29 11:47 UTC, a20hek requested changes
have encountered 2 bugs, can check them out here @Sajal0208 :
https://www.loom.com/share/bfa1af8b19934af19622bc57a0bb49cd?sid=ea5c7b30-bf97-4e4b-8ad6-986dacd68882

2024-03-29 11:55 UTC, Sajal0208 commented
will fix them right away

2024-03-29 14:35 UTC, a20hek requested changes
also, there is no need for two separate endpoints. please do things as necessary

2024-03-29 14:35 UTC, a20hek commented on src/features/listing-builder/components/ListingBuilder/ListingBasic.tsx
> +  const [shouldSlugGenerate, setShouldSlugGenerate] = useState(false);
there is no need for this
all you need to do is rerender only on title change by adding `title` as a dependancy to the useEffect

2024-03-29 15:44 UTC, a20hek commented on src/features/listing-builder/components/ListingBuilder/ListingBasic.tsx
> +  const [shouldSlugGenerate, setShouldSlugGenerate] = useState(false);
no, its the flawed getUniqueSlug function. you are trying to rectify it by adding more code

2024-03-29 17:30 UTC, PratyushSawan commented
Hi @Sajal0208 and @a20hek,
I just want to give feedback on slug generation. I think we don't have to allow any kind of space/special_charcter in the slug.

What you think @a20hek  on this?

2024-03-29 18:02 UTC, a20hek commented
> Hi @Sajal0208 and @a20hek, I just want to give feedback on slug generation. I think we don't have to allow any kind of space/special_charcter in the slug.
> 
> What you think @a20hek on this?

yeah that's correct

2024-03-30 16:00 UTC, a20hek approved these changes

2024-03-30 18:06 UTC, merged