feat: prompt user to install pwa
SuperteamDAO/earn pull request #534
Opened 2024-04-07 20:45 UTC by SkTomsi

## What does this PR do?
closes #533 
## Where should the reviewer start?

## How should this be manually tested?

## Any background context you want to provide?

## What are the relevant issues?

## Screenshots (if appropriate)

2024-04-08 23:40 UTC, a20hek requested changes

2024-04-08 23:40 UTC, a20hek commented on package.json
> +    "next-useragent": "^2.8.0",
i dont think a separate package is needed
from memory, i think android devices can be checked using something like
```
const isAndroid = (): boolean => {
  return /Android/i.test(navigator.userAgent);
};
```

there is something similar for iOS too

2024-04-08 23:40 UTC, a20hek commented on src/pages/index.tsx
> +      // @ts-expect-error --> to remove prompt doesnt exist error
we generally don't encourage `ts-ignore`s and `ts-expect-error`s
so please find a proper typesafe alternative

2024-04-08 23:40 UTC, a20hek commented on src/pages/index.tsx
> +  useEffect(() => {
would be better to show the modal ~30 seconds into opening the site

2024-04-10 14:43 UTC, a20hek approved these changes
lgtm!

2024-04-10 14:47 UTC, merged

2024-04-11 16:17 UTC, a20hek commented
just a heads up. there was just one issue with the pwa check; had to add a few more checks: https://github.com/SuperteamDAO/earn/commit/3cde4fab01a5f711d49bf7f60f43a09952787f0e#diff-18e0d4553c97cfc420e938ccafb4e3a688e782fa4512ba4ceae3e2a6f24c1987L112-R121

have fixed it; but just letting you know @SkTomsi

2024-04-11 17:22 UTC, SkTomsi commented
ahhh i missed my bad, thanks for the addition @a20hek