FEAT: Posthog Events across product
SuperteamDAO/earn pull request #561
Opened 2024-04-25 11:11 UTC by JayeshVP24

## What does this PR do?

## Where should the reviewer start?

## How should this be manually tested?

## Any background context you want to provide?

## What are the relevant issues?

## Screenshots (if appropriate)

2024-05-09 11:23 UTC, a20hek requested changes
`pnpm.lock` file should not have a diff
just pull the latest version from main

2024-05-09 11:29 UTC, JayeshVP24 commented on src/components/home/SideBar.tsx
> +                  posthog.capture('create account_getting started');
we are following the following naming convention here
(event name separated by spaces)(underscore)(location or feature name of event generated at separated by space)

2024-05-24 23:04 UTC, a20hek reviewed
have a question:
if we are capturing pageviews, then what's the need for capturing through useEffect for certain pages?

2024-05-25 06:20 UTC, JayeshVP24 commented on src/features/navbar/components/MobileNavbar.tsx
> -        <Flex gap={{ base: 2, sm: 8, md: 12 }}>
might have accidentally merged old ones, switching back

2024-05-25 06:26 UTC, JayeshVP24 commented
> have a question: if we are capturing pageviews, then what's the need for capturing through useEffect for certain pages?

create funnels in posthog using PageView event is a not easy 
pratik asked for custom names only for the funnels he's making

and sometimes u want event name based on type of page like open_bounty and open_project are same page

2024-05-25 06:33 UTC, JayeshVP24 commented on src/features/listings/components/Submission/SubmissionActionButton.tsx
> +          console.log('submit');
done

2024-05-25 06:33 UTC, JayeshVP24 commented on src/features/listings/components/Submission/SubmissionActionButton.tsx
> +          console.log('edit');
done

2024-05-25 06:33 UTC, JayeshVP24 commented on src/features/navbar/components/MobileNavbar.tsx
> -        <Flex gap={{ base: 2, sm: 8, md: 12 }}>
done

2024-05-25 06:33 UTC, JayeshVP24 commented on src/features/navbar/components/MobileNavbar.tsx
> +        <Flex className="ph-no-capture" gap={{ base: 2, sm: 12 }}>
done

2024-05-25 09:18 UTC, a20hek approved these changes

2024-05-25 09:19 UTC, merged